house/urls.py
from django.urls import path

from house.views import HouseCreateView, HouseDeleteView, HouseListView, HouseUpdateView, ThanksView

app_name = 'house'

urlpatterns = [
    path('', HouseListView.as_view(), name='list'),
    path('add', HouseCreateView.as_view(), name='add'),
    path('delete/<int:house_id>', HouseDeleteView.as_view(), name='delete'),
    path('thanks/', ThanksView.as_view(), name='thanks'),
    path('update/<int:pk>', HouseUpdateView.as_view(), name='update'),
]

payment/urls.py
from django.urls import path

from payment.views import RentPaymentView, PaymentCreateView

urlpatterns = [
    path('payment', RentPaymentView.as_view(), name='payment_list'),
    path('payment/<int:house_id>/<int:year>/<int:month>', PaymentCreateView.as_view(), name='payment_create'),
]

pintokost/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from house import views as house_views
from payment.views import KuitansiView

urlpatterns = [
    path('', house_views.index, name='index'),
    path('admin/', admin.site.urls),
    path('house/', include('house.urls', namespace='house')),
    path('rent/', include('rent.urls', namespace='rent')),
    path('profile/', include('profile.urls', namespace='profile')),
    path('k/<int:pk>/<str:slug>', KuitansiView.as_view(), name='kuitansi'),
    path('login/', auth_views.LoginView.as_view(template_name='house/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),
    path("select2/", include("django_select2.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile/urls.py
from django.urls import path

from profile.views import LandlordSignupView, ProfileCreateView

app_name = 'profile'

urlpatterns = [
    path('landlord/new', LandlordSignupView.as_view(), name='landlord_new'),
    path('renter/new', ProfileCreateView.as_view(), name='create_renter'),
]

rent/urls.py
from django.urls import path

from rent.views import RentCreateView, RentDeleteView


app_name = 'rent'

urlpatterns = [
    path('<int:house_id>', RentCreateView.as_view(), name='create'),
    path('<int:house_id>/deactivate', RentDeleteView.as_view(), name='deactivate'),
]

house/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from pintokost.helpers import resize_image


def house_dir(instance, filename):
    return "house/{0}/{1}".format(instance.owner.username, filename)


class House(models.Model):
    name = models.CharField(max_length=50)
    name_lower = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=300)
    pln_number = models.CharField(max_length=20, blank=True)
    active = models.BooleanField(default=True)
    deleted_at = models.DateTimeField(blank=True, null=True)
    owner = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        limit_choices_to={'groups__name': 'owner'}
    )
    image = models.ImageField(null=True, blank=True, upload_to=house_dir)

    class Meta:
        unique_together = ('name_lower', 'owner')

    def __str__(self):
        return self.name

    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

        from django.templatetags.static import static
        return static('default.jpg')

    def save(self, *args, **kwargs):
        if self.image:
            self.image = resize_image(self.image)
        self.name_lower = self.name.lower()
        super(House, self).save(*args, **kwargs)

    def soft_delete(self):
        self.active = False
        self.deleted_at = timezone.now()
        self.save()

    def is_currently_rented(self):
        from rent.models import Rent
        is_exists = Rent.objects.filter(house=self, active=True).exists()
        return is_exists

    def get_current_rent(self):
        from rent.models import Rent
        profile = Rent.objects.get(house=self, active=True)
        return profile

payment/models.py
from django.db import models

from house.models import House
from rent.models import Rent


def is_already_paid(house: House, year: int, month: int):
    return True


class Payment(models.Model):
    rent = models.ForeignKey(Rent, on_delete=models.PROTECT)
    nominal = models.DecimalField(max_digits=12, default=0, decimal_places=2)
    pay_date = models.DateField(default=None, help_text='Format: YYYY-MM-DD')
    billing_date = models.DateField(default=None, help_text='Format: YYYY-MM-DD')

    objects = models.Manager()

    def __str__(self):
        return "%s/%s (%s)" % (self.rent.house.name, self.billing_date, self.rent.renter)

    @classmethod
    def get_paid(cls, house_owner, year, month):
        return cls.objects.select_related('rent').filter(
            rent__house__owner=house_owner,
            rent__active=True,
            start__year=year,
            start__month=month,
        )

    def kuitansi_obj(pk, year, month, renter_username, owner_username):
        return Payment.objects.select_related('rent__house__owner').get(
            id=pk,
            rent__house__owner__username=owner_username,
            rent__renter__username=renter_username,
            start__year=year,
            start__month=month
        )

    def monthly_income(owner, year, month):
        qs = Payment.objects.filter(
            rent__house__owner=owner,
            start__year=year,
            start__month=month,
        ).aggregate(models.Sum('nominal'))

        return int(qs['nominal__sum'] or 0)

    def nominal_in_rupiah(self):
        return toRupiah(self.nominal)

# def get_sum_payment_of_rent(self, rent: Rent):
# 	return Payment.objects.values('rent').annotate(sum_payment=models.Sum('nominal')).get(
# 		rent__id=rent.id,
# 		start__year=self.payment_set.first().start.year,
# 		start__month=self.payment_set.first().start.month
# 	)['sum_payment']

# def show_debt(self):
# 	return False

# def get_debt(house_owner, year, month):
# 	paid = Payment.get_paid(house_owner, year, month)
# 	return Rent.objects.prefetch_related(models.Prefetch('payment_set', queryset=paid)).filter(
# 		house__owner=house_owner,
# 		active=True,
# 		start_date__lte=datetime.date(int(year), int(month), 15), #ambil pengontrak yg mulai dibawah tanggal 15
# 	).exclude(id__in=paid.annotate(sum_payment=models.Sum('nominal')).filter(sum_payment=models.F('rent__price')).values_list('rent_id', flat=True))

rent/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User

from house.models import House
from pintokost.helpers import toRupiah


class Rent(models.Model):
    renter = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        limit_choices_to={'groups__name': 'renter'}
    )
    house = models.ForeignKey(House, on_delete=models.PROTECT)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    billing_date = models.DateField(default=None)
    active = models.BooleanField(default=True)
    start_date = models.DateField(default=datetime.date.today, help_text='Format: YYYY-MM-DD')
    deleted_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return "%s : %s <%s>" % (self.house.name, self.renter.get_full_name(), toRupiah(self.price))

    def soft_delete(self):
        self.active = False
        self.deleted_at = datetime.date.today
        self.save()

house/forms.py
from django import forms
from .models import House


class HouseForm(forms.ModelForm):
    class Meta:
        model = House
        fields = ['name', 'address', 'pln_number', 'image']
        widgets = {
            'address': forms.Textarea({'rows': 4}),
        }
        labels = {
            'name': 'Nama Rumah',
            'address': 'Alamat Lengkap',
            'pln_number': 'Nomor listrik PLN',
        }

payment/forms.py
from datetime import date

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, HTML
from django import forms
from django.utils.dates import MONTHS


class PaymentListForm(forms.Form):
    START_YEAR = 2021
    year_range = reversed(range(START_YEAR, date.today().year+1))
    year_tuple = [(x, str(x)) for x in year_range]
    year = forms.ChoiceField(choices=year_tuple)

    months = [(x, MONTHS[x]) for x in range(1, 13)]
    month = forms.ChoiceField(choices=months)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Div(
                Div('year', css_class='col'),
                Div('month', css_class='col px-0'),
                Div(    HTML('<button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> Cari</button>'), css_class='col'),
                css_class='row'
            )
        )

house/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .forms import HouseForm
from .mixins import HouseOwnerMixin
from .models import House


def index(request):
    # return redirect(reverse_lazy('house:payment_list'))
    houses = House.objects.filter(owner=request.user)
    context = {
        'houses': houses
    }
    return render(request, "house/index.html", context)


class HouseCreateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = HouseForm
    model = House
    permission_required = 'house.add_house'
    success_url = reverse_lazy('index')
    success_message = "Rumah %(name)s berhasil ditambah"
    template_name = 'house/rent_form.html'

    def get_context_data(self, **kwargs):
        context = super(HouseCreateView, self).get_context_data(**kwargs)
        context['menu_house'] = True
        context['action'] = 'Tambah'
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(HouseCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        try:
            return super().post(request, *args, **kwargs)
        except IntegrityError:
            messages.add_message(request, messages.ERROR,
                                 'Rumah dengan nama {}, sudah ada'.format(request.POST.get('name')))
            return render(request, template_name=self.template_name, context=self.get_context_data())


class HouseDeleteView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, HouseOwnerMixin, DeleteView):
    model = House
    permission_required = 'house.delete_house'
    success_url = reverse_lazy('house:list')
    success_message = "Rumah berhasil dihapus"
    template_name = 'house/delete.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        for rent in self.object.rent_set.filter(active=True):
            rent.soft_delete()
        self.object.soft_delete()
        return HttpResponseRedirect(self.get_success_url())


class HouseListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = House
    permission_required = 'house.view_house'
    template_name = 'house/list.html'

    def get_context_data(self, **kwargs):
        context = super(HouseListView, self).get_context_data(**kwargs)
        context['menu_house'] = True
        return context

    def get_queryset(self):
        return House.objects.filter(owner=self.request.user, active=True)


class HouseUpdateView(LoginRequiredMixin, PermissionRequiredMixin, HouseOwnerMixin, SuccessMessageMixin, UpdateView):
    form_class = HouseForm
    permission_required = 'house.change_house'
    model = House
    success_message = "Rumah %(name)s berhasil diperbarui"
    success_url = reverse_lazy('house:list')
    template_name = 'house/rent_form.html'

    def get_context_data(self, **kwargs):
        context = super(HouseUpdateView, self).get_context_data(**kwargs)
        context['menu_house'] = True
        context['action'] = 'Ubah'
        return context

    def get_form(self, form_class=None):
        form = super(HouseUpdateView, self).get_form(form_class)
        if self.object.village and hasattr(self.object, 'village'):
            form.fields['province'].initial = self.object.village.district.regency.province_id
            form.fields['regency'].initial = self.object.village.district.regency_id
            form.fields['district'].initial = self.object.village.district_id
        return form


class ThanksView(LoginRequiredMixin, TemplateView):
    template_name = 'house/thanks.html'

payment/views.py
from datetime import timezone, date

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.dates import MONTHS
from django.views.generic import CreateView, FormView, DetailView

from expense.models import Expense
from payment.forms import PaymentListForm
from payment.models import Payment
from pintokost.helpers import toRupiah
from rent.models import Rent


class KuitansiView(DetailView):
    model = Payment
    template_name = 'house/kuitansi.html'

    def get_object(self):
        try:
            pk = self.kwargs.get('pk')
            slug = self.kwargs.get('slug')
            slug = slug.split('-')
            return Payment.kuitansi_obj(pk, slug[0], slug[1], slug[2], slug[3])
        except Exception as e:
            raise Http404(e)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['month_name'] = MONTHS[int(self.get_object().start.month)]
        context['nominal'] = toRupiah(self.get_object().nominal)
        context['price'] = toRupiah(self.get_object().rent.price)
        return context


class PaymentCreateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    fields = ['nominal', 'pay_date', 'start']
    model = Payment
    permission_required = 'payment.add_payment'
    rent = None
    success_message = "Pembayaran berhasil disimpan"
    success_url = reverse_lazy('payment:list')

    def get_initial(self):
        self.rent = get_object_or_404(Rent, id=self.kwargs.get('house_id'), house__owner=self.request.user)
        return {
            'rent': self.rent,
            'nominal': int(self.rent.price),
            'pay_date': timezone.now(),
            'start': date(self.kwargs.get('year'), self.kwargs.get('month'), 1)
        }

    def get_context_data(self, **kwargs):
        context = super(PaymentCreateView, self).get_context_data(**kwargs)
        context['rent'] = self.rent
        return context

    def get_form(self, form_class=None):
        form = super(PaymentCreateView, self).get_form(form_class)
        form.fields['nominal'].widget.attrs = {'step': 1000}
        return form

    def form_valid(self, form):
        form.instance.rent = self.rent
        return super(PaymentCreateView, self).form_valid(form)


class RentPaymentView(LoginRequiredMixin, PermissionRequiredMixin, FormView):
    form_class = PaymentListForm
    permission_required = 'rent.view_payment'
    template_name = 'rent/paid_and_debt.html'

    def build_data_context(self, context, year, month):
        context['menu_pembayaran'] = True
        context['month'] = month
        context['month_name'] = MONTHS[int(month)]
        context['year'] = year
        context['debt'] = Rent.get_debt(self.request.user, year, month)
        context['paid'] = Payment.get_paid(self.request.user, year, month)
        income = Payment.monthly_income(self.request.user, year, month)
        context['income'] = toRupiah(income)
        expense = Expense.monthly_outcome(self.request.user, year, month)
        context['expense'] = toRupiah(expense)
        balance = income - expense
        context['balance'] = toRupiah(balance)
        context['balance_css_class'] = 'info' if balance > 0 else 'danger'
        context['slug'] = str(year) + "-" + str(month)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        context = self.build_data_context(context, form.cleaned_data['year'], form.cleaned_data['month'])
        return super(RentPaymentView, self).render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(RentPaymentView, self).get_context_data(**kwargs)
        today = date.today()
        context = self.build_data_context(context, today.year, today.month)
        return context

    def get_initial(self):
        return {
            'year': date.today().year,
            'month': date.today().month,
        }

house/templates/house/base.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>{% block title %}{% endblock %} &raquo; Haven DaruSinau</title>
		<link href="{% static 'custom.min.css' %}" rel="stylesheet">
		<link href="{% static 'bootstrap.flatly.css' %}" rel="stylesheet">
		<link rel="stylesheet" href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
		{% block css %}{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
			<a class="navbar-brand" href="/">Atur Kos</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			{% if user.is_authenticated %}
			<div class="collapse navbar-collapse" id="navbarColor01">
				<ul class="navbar-nav mr-auto">
					{% if perms.house.view_payment %}
					<li class="nav-item {% if menu_pembayaran %}active{% endif %}">
						<a class="nav-link" href="{% url 'house:payment_list' %}"><i class="fa fa-usd"></i> Pembayaran</a>
					</li>
					{% endif %}

					{% if perms.house.add_house %}
					<li class="nav-item {% if menu_house %}active{% endif %}">
						<a class="nav-link" href="{% url 'house:list' %}"><i class="fa fa-building"></i> Properti</a>
					</li>
					{% endif %}

					{% if request.user.is_staff %}
					    <li class="nav-item">
							<a href="{% url 'admin:index' %}" class="nav-link">Admin Page</a>
						</li>
					{% endif %}
				</ul>
				<div class="my-1 my-lg-0">
					<a href="{% url 'logout' %}" class="nav-link"><i class="fa fa-sign-out"></i> Keluar</a>
				</div>
			</div>
			{% else %}
			<div class="collapse navbar-collapse" id="navbarColor01">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" href="https://haven.darusinau.com"><i class="fa fa-building"></i> Haven DaruSinau</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="https://darusinau.com"><i class="fa fa-bolt"></i> Blog DaruSinau</a>
					</li>
				</ul>
			</div>
			{% endif %}
		</nav>
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-8 order-md-first">
					{% block pagecontent %}
					{% endblock %}
				</div>
				
				<div class="col-12 col-md-4 order-first">
					{% block sidecontent %}
					{% endblock %}
				</div>
			</div>
		</div>
		<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
		{% block javascript %}{% endblock %}
	</body>
</html>

house/templates/house/delete.html
{% extends 'house/base.html' %}
{% block title %}Hapus Rumah{% endblock %}

{% block pagecontent %}
	<form method="post">{% csrf_token %}
		<p>Apakah anda yakin ingin menghapus "{{ object }}"?</p>
		<input type="submit" value="Hapus" class="btn btn-danger">
		<a href="{% url 'house:list' %}" class="btn btn-warning">Batal</a>
	</form>
{% endblock %}

house/templates/house/index.html
{% extends 'house/base.html' %}
{% load payment_filter %}

{% block title %}Daftar rumah{% endblock %}

{% block pagecontent %}
    <p class="lead">Daftar Properti</p>
    {% if houses %}
    {% for house in houses %}
    <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">{{house.name}}</h5>
          {% if house.is_currently_rented %}
            <p class="card-text">
                <p><i class="fa fa-user-circle"></i> {{house.get_current_rent.renter.first_name}} &nbsp; <span class="badge badge-pill badge-info"><i class="fa fa-phone"></i> {{house.get_current_rent.renter.profile.phone}}</span></p>
            </p>
            {% is_paid house "2024" "5" as paid %}
            {% if paid  %}
            <a href="#" class="btn btn-success" disabled><i class="fa fa-check-circle-o" aria-hidden="true"></i> Sudah bayar</a>
            {% else %}
            <a href="#" class="btn btn-primary"><i class="fa fa-money" aria-hidden="true"></i> Tandai sudah bayar</a>
            <a href="#" class="btn btn-warning"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> Kirim Tagihan</a>
            {% endif %}
          {% else %}
            <p><i class="text-danger fa fa-minus-circle"></i> Sedang kosong</p>
            <a href="#" class="btn btn-primary"><i class="fa fa-cog" aria-hidden="true"></i> Atur Penyewa</a>
          {% endif %}
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p class="lead">masih kosong</p>
    {% endif %}
{% endblock pagecontent %}
{% block sidecontent %}
<div class="row">
    <div class="col-12">
        <small>Pilih bulan dan tahun untuk cek status pembayaran</small>
    </div>
</div>
<div class="row">
        <div class="dropdown col-4">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Tahun
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="#">2024</a>
            </div>
        </div>
        <div class="dropdown col-4">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Bulan
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="#">Januari</a>
              <a class="dropdown-item" href="#">Februari</a>
              <a class="dropdown-item" href="#">Maret</a>
              <a class="dropdown-item" href="#">April</a>
              <a class="dropdown-item" href="#">Mei</a>
            </div>
        </div>
        <button type="button" class="btn btn-info">
            <i class="fa fa-search"></i> Cari
        </button>
</div>
<hr class="my-2"/>
<div class="row">
    <div class="col-12">
        <small>Untuk menambah rumah baru, klik tombol di bawah ini</small>
    </div>
</div>
<div class="row mb-2">
    <div class="col-12">
        <a href="{% url 'house:add' %}" class="col-12 btn btn-primary"><i class="fa fa-plus"></i> Tambah rumah baru </a>
    </div>
</div>
<hr class="my-2"/>
{% include 'house/messages.html' %}
{% endblock sidecontent %}

house/templates/house/list.html
{% extends 'house/base.html' %}
{% block title %}Daftar Rumah{% endblock %}

{% block pagecontent %}
	{% if messages %}
		{% for message in messages %}
		<div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
		{% endfor %}
	{% endif %}
	{% for object in object_list %}
		<div class="card mb-3">
			<div class="row no-gutters">
				<div class="col-auto">
					<img src="{{ object.image_url }}" width="100" class="img-fluid" alt="img of {{object.name}}">
				</div>
				<div class="col">
					<div class="card-block px-2 pb-2">
						<h4 class="card-title">{{object.name}}</h4>
						<p class="card-text">{{object.address}}</p>
						<a href="{% url 'house:update' object.id %}" class="btn btn-info btn-sm">Ubah</a>
						<a href="{% url 'house:delete' object.id %}" class="btn btn-danger btn-sm">Hapus</a>
						&nbsp
						&nbsp
						<a href="{% url 'house:rent' object.id %}" class="btn btn-warning btn-sm">Atur Penyewa</a>
					</div>
				</div>
			</div>
			<div class="card-footer w-100 text-muted">
				{% for rent in object.rent_set.all %}
					{% if rent.active %}
						{{rent}}
					{% endif %}
				{% endfor %}
			</div>
		</div>
	{% empty %}
		<p>Daftar rumah masih kosong, Anda belum mencatat rumah.</p>
	{% endfor %}
{% endblock %}

{% block sidecontent %}
	<div class="row">
		<div class="col"><a href="{% url 'house:add' %}" class="btn btn-primary">Tambah Rumah</a></div>
	</div>
{% endblock %}

house/templates/house/login.html
{% extends 'house/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}
{% block pagecontent %}
<div class="row justify-content-center align-items-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <form method="POST" autocomplete="off">
                	{% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" id="sendlogin" class="btn btn-primary"><i class="fa fa-sign-in"></i> Masuk</button>
                    &nbsp
                    <a href="{% url 'profile:landlord_new' %}" class="btn btn-success"><i class="fa fa-wpforms"></i> Daftar</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

house/templates/house/payment_form.html
{% extends 'house/base.html' %}
{% block title %}Pembayaran{% endblock %}
{% load crispy_forms_tags %}

{% block pagecontent %}
	<h4>Pembayaran <b>{{rent}}</b></h4>
	<form method="POST">
		{% csrf_token %}
		{{ form | crispy }}
		<button type="submit" class="btn btn-primary">Simpan</button>
	</form>
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" />
{% endblock %}

{% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous"></script>
<script type="text/javascript">
  var datepicker_opt = {
      format: "yyyy-mm-dd",
      maxViewMode: 3,
      todayBtn: "linked",
      orientation: "bottom auto",
      autoclose: true
  }
	$('#id_pay_date').datepicker(datepicker_opt);
	$('#id_start').datepicker(datepicker_opt);
</script>
{% endblock %}